use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=bootloader.toml");
    println!("cargo:rerun-if-changed=programs/");

    generate_programs_rs();
}

fn generate_programs_rs() {
    let programs_dir = Path::new("programs");
    let out_path = Path::new("src/programs.rs");

    // Collect .aleph files
    let mut aleph_files: Vec<String> = fs::read_dir(programs_dir)
        .expect("programs/ directory not found")
        .filter_map(|e| {
            let e = e.ok()?;
            let name = e.file_name().into_string().ok()?;
            if name.ends_with(".aleph") { Some(name) } else { None }
        })
        .collect();
    aleph_files.sort();

    // Collect .imasm files
    let mut imasm_files: Vec<String> = fs::read_dir(programs_dir)
        .expect("programs/ directory not found")
        .filter_map(|e| {
            let e = e.ok()?;
            let name = e.file_name().into_string().ok()?;
            if name.ends_with(".imasm") { Some(name) } else { None }
        })
        .collect();
    imasm_files.sort();

    let mut out = String::new();
    out.push_str("//! Built-in programs (ALEPH + IMASM) — auto-generated by build.rs.\n");
    out.push_str("//!\n");
    out.push_str("//! Drop any .aleph or .imasm file into programs/ and rebuild.\n\n");

    out.push_str("/// A built-in program: (filename, raw bytes).\n");
    out.push_str("pub struct BuiltinProgram {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub data: &'static [u8],\n");
    out.push_str("}\n\n");

    // ALEPH programs
    out.push_str("pub static PROGRAMS: &[BuiltinProgram] = &[\n");
    for name in &aleph_files {
        out.push_str(&format!(
            "    BuiltinProgram {{ name: {:?}, data: include_bytes!(\"../programs/{}\") }},\n",
            name, name
        ));
    }
    out.push_str("];\n\n");

    // IMASM programs
    out.push_str("pub static IMASM_PROGRAMS: &[BuiltinProgram] = &[\n");
    for name in &imasm_files {
        out.push_str(&format!(
            "    BuiltinProgram {{ name: {:?}, data: include_bytes!(\"../programs/{}\") }},\n",
            name, name
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Write all built-in programs to ALFS, always overwriting.\n");
    out.push_str("/// Call this after `alfs::mount()` succeeds.\n");
    out.push_str("pub fn seed_alfs() {\n");
    out.push_str("    for prog in PROGRAMS {\n");
    out.push_str("        let _ = crate::alfs::write_file(prog.name, prog.data, crate::alfs::TYPE_ALEPH);\n");
    out.push_str("    }\n");
    out.push_str("    for prog in IMASM_PROGRAMS {\n");
    out.push_str("        let _ = crate::alfs::write_file(prog.name, prog.data, crate::alfs::TYPE_ALEPH);\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Look up an IMASM program by name and return its text, or None.\n");
    out.push_str("pub fn load_imasm(name: &str) -> Option<&'static str> {\n");
    out.push_str("    IMASM_PROGRAMS.iter()\n");
    out.push_str("        .find(|p| p.name == name || p.name.trim_end_matches(\".imasm\") == name)\n");
    out.push_str("        .and_then(|p| core::str::from_utf8(p.data).ok())\n");
    out.push_str("}\n");

    let existing = fs::read_to_string(out_path).unwrap_or_default();
    if existing != out {
        fs::write(out_path, &out).expect("failed to write src/programs.rs");
    }
}
