use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=bootloader.toml");
    println!("cargo:rerun-if-changed=programs/");

    generate_programs_rs();
}

fn generate_programs_rs() {
    let programs_dir = Path::new("programs");
    let out_path = Path::new("src/programs.rs");

    // Collect all .aleph files, sorted for deterministic output.
    let mut files: Vec<String> = fs::read_dir(programs_dir)
        .expect("programs/ directory not found")
        .filter_map(|e| {
            let e = e.ok()?;
            let name = e.file_name().into_string().ok()?;
            if name.ends_with(".aleph") { Some(name) } else { None }
        })
        .collect();
    files.sort();

    let mut out = String::new();
    out.push_str("//! Built-in ALEPH programs — auto-generated by build.rs.\n");
    out.push_str("//!\n");
    out.push_str("//! Drop any .aleph file into programs/ and rebuild — it will be\n");
    out.push_str("//! compiled into the kernel and seeded to ALFS on first boot.\n");
    out.push_str("//! Do not edit this file manually; changes will be overwritten.\n\n");

    out.push_str("/// A built-in program: (filename, raw bytes).\n");
    out.push_str("pub struct BuiltinProgram {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub data: &'static [u8],\n");
    out.push_str("}\n\n");

    out.push_str("pub static PROGRAMS: &[BuiltinProgram] = &[\n");
    for name in &files {
        out.push_str(&format!(
            "    BuiltinProgram {{ name: {:?}, data: include_bytes!(\"../programs/{}\") }},\n",
            name, name
        ));
    }
    out.push_str("];\n\n");

    out.push_str("/// Write all built-in programs to ALFS, always overwriting.\n");
    out.push_str("/// Call this after `alfs::mount()` succeeds.\n");
    out.push_str("pub fn seed_alfs() {\n");
    out.push_str("    for prog in PROGRAMS {\n");
    out.push_str("        let _ = crate::alfs::write_file(prog.name, prog.data, crate::alfs::TYPE_ALEPH);\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    let existing = fs::read_to_string(out_path).unwrap_or_default();
    if existing != out {
        fs::write(out_path, &out).expect("failed to write src/programs.rs");
    }
}
