//! Command grammar (from Hebrew Sefer Yetzirah + Varnamala pratyahara).
//!
//! Commands are NOT imperative strings but **generative letter-combinations**:
//! - A command is a tensor product of letter-primitives that generates its own
//!   execution context
//! - The pratyahara principle: any subset of command primitives can be referenced
//!   by a single index, compressing complex pipeline compositions into atomic tokens
//!
//! This is the Sefer Yetzirah model: letters are morphisms between ontological
//! categories, not labels. Gematria is a distance metric in the 12-primitive space.

use alloc::vec::Vec;

/// Command primitive — a generator of execution context
/// Modeled after the Hebrew letter-primitives: each letter is a structural
/// transformation, not an instruction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandPrimitive {
    /// Aleph (א): The silent opener — creates a new context/scope
    /// Ω_Z protected, Φ_c critical
    Aleph,
    /// Mem (מ): The water — flows, connects, propagates
    /// O_inf, recursive
    Mem,
    /// Shin (ש): The fire — transforms, consumes
    /// O_inf, energetic
    Shin,
    /// Vav (ו): The hook — links, chains, sequences
    /// O_inf, connects heaven to earth
    Vav,
    /// Bet (ב): The house — contains, houses, scopes
    Bet,
    /// Gimel (ג): The camel — carries, transfers
    Gimel,
    /// Dalet (ד): The door — gates, opens, closes
    Dalet,
    /// Heh (ה): The window — observes, reveals
    Heh,
}

impl CommandPrimitive {
    /// The Gematria value (traditional ordinal) — a distance metric in type space
    pub fn gematria(&self) -> u32 {
        match self {
            Self::Aleph => 1,
            Self::Bet => 2,
            Self::Gimel => 3,
            Self::Dalet => 4,
            Self::Heh => 5,
            Self::Vav => 6,
            Self::Mem => 40,
            Self::Shin => 300,
        }
    }
}

/// A command is a tensor product of primitives — it generates its own execution context
#[derive(Debug, Clone)]
pub struct GenerativeCommand {
    /// The sequence of primitives being tensored together
    pub primitives: Vec<CommandPrimitive>,
    /// Pratyahara index: any subset can be referenced by a single index
    /// This compresses complex pipeline compositions into atomic tokens
    pub pratyahara_index: u16,
    /// Whether this command has generated its context yet
    pub context_generated: bool,
}

impl GenerativeCommand {
    pub fn new(primitives: Vec<CommandPrimitive>) -> Self {
        // Compute pratyahara index as the sum of gematria values
        // This is the distance metric in the 12-primitive space
        let pratyahara_index = primitives
            .iter()
            .map(|p| p.gematria())
            .sum::<u32>() as u16;

        Self {
            primitives,
            pratyahara_index,
            context_generated: false,
        }
    }

    /// Generate the execution context from the tensor product of primitives
    pub fn generate_context(&mut self) -> CommandContext {
        self.context_generated = true;
        CommandContext {
            pratyahara_index: self.pratyahara_index,
            priority: self.primitives.len() as u8,
            has_aleph: self.primitives.contains(&CommandPrimitive::Aleph),
        }
    }

    /// The total gematria distance — the "weight" of this command in type space
    pub fn total_gematria(&self) -> u32 {
        self.primitives
            .iter()
            .map(|p| p.gematria())
            .sum()
    }
}

/// The execution context generated by a command
/// This is not part of the command itself — it's the environment the command creates
#[derive(Debug, Clone)]
pub struct CommandContext {
    pub pratyahara_index: u16,
    pub priority: u8,
    /// If Aleph is present, a new scope/context is created
    pub has_aleph: bool,
}
