//! Built-in programs (ALEPH + IMASM) — auto-generated by build.rs.
//!
//! Drop any .aleph or .imasm file into programs/ and rebuild.

/// A built-in program: (filename, raw bytes).
pub struct BuiltinProgram {
    pub name: &'static str,
    pub data: &'static [u8],
}

pub static PROGRAMS: &[BuiltinProgram] = &[
    BuiltinProgram { name: "coupling_destruction.aleph", data: include_bytes!("../programs/coupling_destruction.aleph") },
    BuiltinProgram { name: "creation.aleph", data: include_bytes!("../programs/creation.aleph") },
    BuiltinProgram { name: "creation_liturgy.aleph", data: include_bytes!("../programs/creation_liturgy.aleph") },
    BuiltinProgram { name: "distance_probes_indistinguishable.aleph", data: include_bytes!("../programs/distance_probes_indistinguishable.aleph") },
    BuiltinProgram { name: "exploration_primitives.aleph", data: include_bytes!("../programs/exploration_primitives.aleph") },
    BuiltinProgram { name: "frobenius.aleph", data: include_bytes!("../programs/frobenius.aleph") },
    BuiltinProgram { name: "frobenius_orbits.aleph", data: include_bytes!("../programs/frobenius_orbits.aleph") },
    BuiltinProgram { name: "holographic_monitor.aleph", data: include_bytes!("../programs/holographic_monitor.aleph") },
    BuiltinProgram { name: "light_replication_kernel.aleph", data: include_bytes!("../programs/light_replication_kernel.aleph") },
    BuiltinProgram { name: "light_stability.aleph", data: include_bytes!("../programs/light_stability.aleph") },
    BuiltinProgram { name: "meditation.aleph", data: include_bytes!("../programs/meditation.aleph") },
    BuiltinProgram { name: "phi_ep_probe.aleph", data: include_bytes!("../programs/phi_ep_probe.aleph") },
    BuiltinProgram { name: "pratyahara.aleph", data: include_bytes!("../programs/pratyahara.aleph") },
    BuiltinProgram { name: "selfreplicating_light.aleph", data: include_bytes!("../programs/selfreplicating_light.aleph") },
    BuiltinProgram { name: "tikkun_construction_full.aleph", data: include_bytes!("../programs/tikkun_construction_full.aleph") },
    BuiltinProgram { name: "tikkun_construction_partial.aleph", data: include_bytes!("../programs/tikkun_construction_partial.aleph") },
    BuiltinProgram { name: "tikkun_palace_verification.aleph", data: include_bytes!("../programs/tikkun_palace_verification.aleph") },
];

pub static IMASM_PROGRAMS: &[BuiltinProgram] = &[
    BuiltinProgram { name: "cross_distance.imasm", data: include_bytes!("../programs/cross_distance.imasm") },
    BuiltinProgram { name: "linear_a_bootstrap.imasm", data: include_bytes!("../programs/linear_a_bootstrap.imasm") },
    BuiltinProgram { name: "rohonc_bootstrap.imasm", data: include_bytes!("../programs/rohonc_bootstrap.imasm") },
    BuiltinProgram { name: "voynich_bootstrap.imasm", data: include_bytes!("../programs/voynich_bootstrap.imasm") },
];

/// Write all built-in programs to ALFS, always overwriting.
/// Call this after `alfs::mount()` succeeds.
pub fn seed_alfs() {
    for prog in PROGRAMS {
        let _ = crate::alfs::write_file(prog.name, prog.data, crate::alfs::TYPE_ALEPH);
    }
    for prog in IMASM_PROGRAMS {
        let _ = crate::alfs::write_file(prog.name, prog.data, crate::alfs::TYPE_ALEPH);
    }
}

/// Look up an IMASM program by name and return its text, or None.
pub fn load_imasm(name: &str) -> Option<&'static str> {
    IMASM_PROGRAMS.iter()
        .find(|p| p.name == name || p.name.trim_end_matches(".imasm") == name)
        .and_then(|p| core::str::from_utf8(p.data).ok())
}
